In [1]:
import numpy as np

def none_zero(arr):
    return np.all(arr != 0)

arr = np.array([1, 2, 3, 4, 5])
print(none_zero(arr))  

arr = np.array([1, 2, 0, 4, 5])
print(none_zero(arr))  


True
False


In [2]:
def any_non_zero(arr):
    return np.any(arr != 0)

arr = np.array([0, 0, 0, 0, 0])
print(any_non_zero(arr))  

arr = np.array([0, 0, 3, 0, 0])
print(any_non_zero(arr))  


False
True


In [5]:
def element_wise_comparison(arr1, arr2, tol=1e-8):
    return np.isclose(arr1, arr2, atol=tol)

arr1 = np.array([1, 2, 3])
arr2 = np.array([1.01, 2.01, 3.01])
print(element_wise_comparison(arr1, arr2))  


[False False False]


In [6]:

arr = np.concatenate((np.zeros(10), np.ones(10), np.ones(10) * 5))
print(arr)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 5. 5. 5. 5.
 5. 5. 5. 5. 5. 5.]


In [7]:
arr = np.arange(30, 71)
print(arr)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [9]:
arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
x = np.random.rand()
print(x)

0.5012401371269909


In [13]:
arr = np.random.rand(15)
print(arr)


[0.59011387 0.89510817 0.2847897  0.12228478 0.54463189 0.5641689
 0.44235611 0.76959785 0.23460362 0.37041362 0.07417219 0.02338748
 0.38902701 0.86168512 0.40262835]


In [14]:
vector = np.arange(15, 56)
print(vector[1:-1])

[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


In [15]:
vector = np.random.randint(0, 11, size=5)
print(vector)

[2 2 4 0 6]


In [17]:
arr = np.zeros((10,10))
arr[0,:] = 1
arr[-1,:] = 1
arr[:,0] = 1
arr[:,-1] = 1
print(arr)


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [18]:
arr = np.diag(np.arange(1, 6))
print(arr)


[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [20]:
arr = np.zeros((4,4))
arr[::2, 1::2] = 1
arr[1::2, ::2] = 1
print(arr)

[[0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]]


In [23]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

np.savez_compressed('arrays.npz', array1=array1, array2=array2)

loaded_data = np.load('arrays.npz')
array1_loaded = loaded_data['array1']
array2_loaded = loaded_data['array2']

print(loaded_data)
print("Array 1:", array1_loaded)
print("Array 2:", array2_loaded)

NpzFile 'arrays.npz' with keys: array1, array2
Array 1: [1 2 3]
Array 2: [4 5 6]


In [25]:
random_array = np.random.rand(40)
print(random_array)

[0.82877889 0.03935351 0.20938485 0.46391157 0.21617099 0.52282232
 0.06583719 0.48437398 0.67922346 0.40681089 0.97420782 0.27815027
 0.65189929 0.75476685 0.15695535 0.51810389 0.51951888 0.48612209
 0.9188387  0.20587243 0.50830953 0.5533929  0.14617893 0.85047902
 0.14666205 0.30068391 0.13037474 0.92922279 0.85592789 0.10519042
 0.74863668 0.09925916 0.50234953 0.5787616  0.07461818 0.61541847
 0.19071584 0.01510085 0.37734422 0.79050061]


In [30]:
def extract_numbers(arr, num):
    less_than = arr[arr < num]
    greater_than = arr[arr > num]
    return less_than, greater_than

arr = np.array([8,4,7,2,1,3,9,8])
num = int(input(print("enter number:")))
less_than_num, greater_than_num = extract_numbers(arr, num)

print("Numbers less than", num, ":", less_than_num)
print("Numbers greater than", num, ":", greater_than_num)

enter number:
Numbers less than 5 : [4 2 1 3]
Numbers greater than 5 : [8 7 9 8]
